resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      item:
        baseConfig: default
  timelimiter:
    configs:
        default:
            timeoutDuration: 6s
    instances:
        item:
            baseConfig: default